OSRT_JSON_RTOBJECTS = \
$(OBJDIR)$(PS)rtJsonParser$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecAny$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecBase64Str$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecDynBase64Str$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecBool$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecDateTime$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecDecimal$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecDouble$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecDynHexStr$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecHexStr$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecInt64$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecInt32$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecInt16$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecInt8$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecNumberString$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecString$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecUCS2String$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecUCS4String$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecUInt64$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecUInt32$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecUInt16$(OBJ) \
$(OBJDIR)$(PS)rtJsonDecUInt8$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncAnyAttr$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncBase64Binary$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncBool$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncDates$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncDateTime$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncDecimal$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncDouble$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncFloat$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncHexBinary$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncIndent$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncInt$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncInt64$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncString$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncUInt$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncUInt64$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncUCS4String$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncUnicode$(OBJ) \
$(OBJDIR)$(PS)rtJsonEncEdges$(OBJ)
