OSRT_CBOR_RTOBJECTS = \
$(OBJDIR)$(PS)rtCborDecArray$(OBJ) \
$(OBJDIR)$(PS)rtCborDecBase64$(OBJ) \
$(OBJDIR)$(PS)rtCborDecDynBase64$(OBJ) \
$(OBJDIR)$(PS)rtCborDecBigFloat$(OBJ) \
$(OBJDIR)$(PS)rtCborDecBigInt$(OBJ) \
$(OBJDIR)$(PS)rtCborDecByteStr$(OBJ) \
$(OBJDIR)$(PS)rtCborDecDynByteStr$(OBJ) \
$(OBJDIR)$(PS)rtCborDecDateTimeStr$(OBJ) \
$(OBJDIR)$(PS)rtCborDecFloat$(OBJ) \
$(OBJDIR)$(PS)rtCborDecInt16$(OBJ) \
$(OBJDIR)$(PS)rtCborDecInt32$(OBJ) \
$(OBJDIR)$(PS)rtCborDecInt64$(OBJ) \
$(OBJDIR)$(PS)rtCborDecMap$(OBJ) \
$(OBJDIR)$(PS)rtCborDecSize$(OBJ) \
$(OBJDIR)$(PS)rtCborDecSkipField$(OBJ) \
$(OBJDIR)$(PS)rtCborDecTime$(OBJ) \
$(OBJDIR)$(PS)rtCborDecTimeValue$(OBJ) \
$(OBJDIR)$(PS)rtCborDecUInt16$(OBJ) \
$(OBJDIR)$(PS)rtCborDecUInt32$(OBJ) \
$(OBJDIR)$(PS)rtCborDecUInt64$(OBJ) \
$(OBJDIR)$(PS)rtCborDecUTF8Str$(OBJ) \
$(OBJDIR)$(PS)rtCborDecDynUTF8Str$(OBJ) \
$(OBJDIR)$(PS)rtCborDecValue$(OBJ) \
$(OBJDIR)$(PS)rtCborEncArray$(OBJ) \
$(OBJDIR)$(PS)rtCborEncBase64$(OBJ) \
$(OBJDIR)$(PS)rtCborEncBigFloat$(OBJ) \
$(OBJDIR)$(PS)rtCborEncBigInt$(OBJ) \
$(OBJDIR)$(PS)rtCborEncByteStr$(OBJ) \
$(OBJDIR)$(PS)rtCborEncDateTimeStr$(OBJ) \
$(OBJDIR)$(PS)rtCborEncDecSimple$(OBJ) \
$(OBJDIR)$(PS)rtCborEncFloat$(OBJ) \
$(OBJDIR)$(PS)rtCborEncInt32$(OBJ) \
$(OBJDIR)$(PS)rtCborEncInt64$(OBJ) \
$(OBJDIR)$(PS)rtCborEncMap$(OBJ) \
$(OBJDIR)$(PS)rtCborEncNumberStr$(OBJ) \
$(OBJDIR)$(PS)rtCborEncSize$(OBJ) \
$(OBJDIR)$(PS)rtCborEncTime$(OBJ) \
$(OBJDIR)$(PS)rtCborEncTimeValue$(OBJ) \
$(OBJDIR)$(PS)rtCborEncUInt32$(OBJ) \
$(OBJDIR)$(PS)rtCborEncUInt64$(OBJ) \
$(OBJDIR)$(PS)rtCborEncUTF8Str$(OBJ) \
$(OBJDIR)$(PS)rtCborEncValue$(OBJ)
