RTXOBJECTS = \
$(OBJDIR)$(PS)context$(OBJ) \
$(OBJDIR)$(PS)file$(OBJ) \
$(OBJDIR)$(PS)membuf$(OBJ) \
$(OBJDIR)$(PS)memmgmt$(OBJ) \
$(OBJDIR)$(PS)rtxBase64$(OBJ) \
$(OBJDIR)$(PS)rtxBigFloat$(OBJ) \
$(OBJDIR)$(PS)rtxBigInt$(OBJ) \
$(OBJDIR)$(PS)rtxBigIntCommon$(OBJ) \
$(OBJDIR)$(PS)rtxCharStr$(OBJ) \
$(OBJDIR)$(PS)rtxDList$(OBJ) \
$(OBJDIR)$(PS)rtxDateTime$(OBJ) \
$(OBJDIR)$(PS)rtxDateTimeCompare$(OBJ) \
$(OBJDIR)$(PS)rtxDateTimeParse$(OBJ) \
$(OBJDIR)$(PS)rtxDateTimeParseCommon$(OBJ) \
$(OBJDIR)$(PS)rtxDateTimeToString$(OBJ) \
$(OBJDIR)$(PS)rtxDateTimeToStringCommon$(OBJ) \
$(OBJDIR)$(PS)rtxError$(OBJ) \
$(OBJDIR)$(PS)rtxGenValueType$(OBJ) \
$(OBJDIR)$(PS)rtxHexDump$(OBJ) \
$(OBJDIR)$(PS)rtxHexDumpFile$(OBJ) \
$(OBJDIR)$(PS)rtxIntToCharStr$(OBJ) \
$(OBJDIR)$(PS)rtxInt64ToCharStr$(OBJ) \
$(OBJDIR)$(PS)rtxIntStack$(OBJ) \
$(OBJDIR)$(PS)rtxPrint$(OBJ) \
$(OBJDIR)$(PS)rtxRealHelper$(OBJ) \
$(OBJDIR)$(PS)rtxSizeToCharStr$(OBJ) \
$(OBJDIR)$(PS)rtxSList$(OBJ) \
$(OBJDIR)$(PS)rtxStack$(OBJ) \
$(OBJDIR)$(PS)rtxUIntToCharStr$(OBJ) \
$(OBJDIR)$(PS)rtxUInt64ToCharStr$(OBJ) \
$(OBJDIR)$(PS)rtxUTF8$(OBJ)
